{% set version = "0.6.2" %}

package:
  name: dbdreader
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/dbdreader/dbdreader-{{ version }}.tar.gz
  sha256: 8688ca85b2d58abcf4f0a7651ff83b6595d47b1f8fe63bb0a2bf52d8825ad3f8

build:
  skip: true  # [py<310]
  entry_points:
    - dbdrename = dbdreader.scripts:dbdrename
    - cac_gen = dbdreader.scripts:cac_gen
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    # cross-compilation helpers (needed to build osx-arm64 from osx-64)
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - python
    - setuptools >=61.0
    - wheel
    - pip
    - numpy
  run:
    - python
    - lz4 >=4.4.5

test:
  imports:
    - dbdreader
  commands:
    - pip check
    - dbdrename --help
    - cac_gen --help
  requires:
    - pip
    - python

about:
  home: https://dbdreader.readthedocs.io/en/latest/
  summary: A python module to access binary data files generated by Teledyne WebbResearch gliders
  license: GPL-3.0-or-later AND BSD-2-Clause
  license_file:
    - LICENSE
    - COPYING
    - COPYRIGHT

extra:
  recipe-maintainers:
    - jklymak
    - smerckel
